config/routes.rb
Rails.application.routes.draw do
  get "/tasks", to: "tasks#index", as: :tasks
  get "/tasks/new", to: "tasks#new", as: :new_task
  post '/tasks', to: 'tasks#create' #POST /tasks
  get "/tasks/:id", to: "tasks#show", as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create #does not have a view
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  private
  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
@import url('https://fonts.googleapis.com/css?family=Fjalla+One&display=swap');
</style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks!</h1>

<p id="create-item-link">
  <i class="fa fa-plus" aria-hidden="true"></i>
  <%= link_to 'Create a new item', new_task_path, class: "home-link" %></p>

<ul>
<% @tasks.each do |task| %>
  <li><i class="fa fa-check-square" aria-hidden="true"></i>
    <%= link_to task.title, task_path(task), class: "task-list"%></li>
  <br>
<% end %>
</ul>
</div>

app/views/tasks/new.html.erb
<h1>Create a new task here</h1>

<div class="container">
<%= form_for@task do |f| %>
<div class="form-group">
  <%= f.label :Task %>
  <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :details %>
  <%= f.text_field :details, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-warning" %>
<% end %>
<p><%= link_to 'Back to list', tasks_path %></p>
</div>

app/views/tasks/show.html.erb
<h1>New Task!</h1>

<p><%= @task.details %></p>

<p><%= link_to 'Back to list', tasks_path, class: "home-link" %></p>